### ISSUE TITLE
SendBufferSize of 0 causes SocketException in OS-X

### ISSUE THREAD

**Issue by simonjduff** [justeat/JustEat.StatsD#42]
Repro:

```
using System;
using System.Net.Sockets;
namespace simon
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
		var socket = new UdpClient{Client = {SendBufferSize=0}};
        }
    }
}
````

when run results in

````
Unhandled Exception: System.Net.Sockets.SocketException: Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_SendBufferSize(Int32 value)
   at simon.Program.Main(String[] args) in /Users/tom.maton/Dev/simon/Program.cs:line 10
````

https://github.com/justeat/JustEat.StatsD/blob/df3aff460c4bb71f8a14042ea97c2df1b8f51fae/src/JustEat.StatsD/UdpTransport.cs#L51

**Comment by martincostello** [comment]
If we can't write a test that repros this on Linux in Travis CI, we could ask them to enable macOS builds in parallel as well as part of the Travis CI and test this on three platforms instead of two.

**Comment by simonjduff** [comment]
I've just tried the same in an Ubuntu 16.04 VM with no repro, so it looks like just an OS-X issue.
Obviously unlikely to affect production applications, but this issue interrupts the developer experience when working with dotnet core on OS-X.

**Comment by martincostello** [comment]
Cool - I'll see if I can get Travis to enable macOS builds.

**Comment by martincostello** [comment]
Request sent to `support@travis-ci.com`.
